### ISSUE TITLE
pergunta técnica

### ISSUE THREAD

**Issue by ghost** [felipenlunkes/Lunix#4]

**Comment by felipenlunkes** [comment]
E aí! Obrigado pela pergunta e interesse. O Lunix é um kernel feito do zero. O Linux é um kernel com anos de desenvolvimento e suporte a uma variedade de arquiteturas e funcionalidades. O Lunix é, nesse momento, um kernel extremamente pequeno, que consegue ler arquivos de um initrd e tem um console no ambiente do kernel. Ainda não há suporte para outros sistemas de arquivos, e é um projeto extremamente inicial.

**Comment by felipenlunkes** [comment]
@stokebreakup 
Para um sistema mais completo e maduro, tenho um feito em Assembly x86, que desenvolvo mais ativamente. Pode ser encontrado aqui: https://github.com/hexagonix
